const data=[{"country":"France","city":"Albi","rental_name":"Loomis","date_available":6,"price_per_night":403,"stars":4.39},
{"country":"Poland","city":"Raczki","rental_name":"Fremont","date_available":6,"price_per_night":470,"stars":2.66},
{"country":"Vietnam","city":"Quảng Ngãi","rental_name":"Porter","date_available":7,"price_per_night":440,"stars":1.55},
{"country":"China","city":"Huangzhou","rental_name":"Nancy","date_available":5,"price_per_night":570,"stars":1.86},
{"country":"China","city":"Fuquan","rental_name":"Burning Wood","date_available":5,"price_per_night":81,"stars":3.05},
{"country":"China","city":"Gaowu","rental_name":"Norway Maple","date_available":9,"price_per_night":139,"stars":1.44},
{"country":"Mexico","city":"El Mirador","rental_name":"Spenser","date_available":7,"price_per_night":535,"stars":3.99},
{"country":"Brazil","city":"Santo Antônio de Jesus","rental_name":"Old Gate","date_available":6,"price_per_night":306,"stars":1.94},
{"country":"Venezuela","city":"Tinaco","rental_name":"Cambridge","date_available":2,"price_per_night":488,"stars":3.23},
{"country":"Canada","city":"Okanagan","rental_name":"Vera","date_available":10,"price_per_night":249,"stars":1.71},
{"country":"Philippines","city":"Upper San Mateo","rental_name":"Logan","date_available":8,"price_per_night":382,"stars":4.57},
{"country":"Indonesia","city":"Tarutung","rental_name":"Harper","date_available":4,"price_per_night":330,"stars":4.69},
{"country":"Honduras","city":"Cololaca","rental_name":"Knutson","date_available":8,"price_per_night":665,"stars":2.7},
{"country":"Saint Kitts and Nevis","city":"Basseterre","rental_name":"Forest Run","date_available":6,"price_per_night":416,"stars":3.65},
{"country":"Peru","city":"La Esperanza","rental_name":"Arrowood","date_available":3,"price_per_night":770,"stars":4.82},
{"country":"Russia","city":"Lazarevskoye","rental_name":"Lunder","date_available":8,"price_per_night":84,"stars":4.29},
{"country":"France","city":"Lunéville","rental_name":"Calypso","date_available":5,"price_per_night":918,"stars":1.28},
{"country":"Greece","city":"Tríkeri","rental_name":"Crescent Oaks","date_available":1,"price_per_night":990,"stars":1.52},
{"country":"China","city":"Rendian","rental_name":"Hooker","date_available":10,"price_per_night":900,"stars":2.91},
{"country":"Syria","city":"Kuwayris Sharqī","rental_name":"Troy","date_available":6,"price_per_night":258,"stars":3.1},
{"country":"Aruba","city":"Oranjestad","rental_name":"Lien","date_available":10,"price_per_night":677,"stars":1.33},
{"country":"India","city":"Sadar Bazar","rental_name":"Memorial","date_available":5,"price_per_night":203,"stars":3.09},
{"country":"Georgia","city":"Tsinandali","rental_name":"Buena Vista","date_available":6,"price_per_night":208,"stars":2.82},
{"country":"China","city":"Benzilan","rental_name":"Riverside","date_available":1,"price_per_night":294,"stars":3.9},
{"country":"Russia","city":"Kamenka","rental_name":"Drewry","date_available":7,"price_per_night":338,"stars":3.92},
{"country":"Indonesia","city":"Purwodadi","rental_name":"Birchwood","date_available":2,"price_per_night":827,"stars":2.33},
{"country":"Russia","city":"Valerik","rental_name":"Monica","date_available":3,"price_per_night":810,"stars":2.2},
{"country":"Ukraine","city":"Tyvriv","rental_name":"Florence","date_available":10,"price_per_night":604,"stars":3.32},
{"country":"China","city":"Shanmei","rental_name":"Clarendon","date_available":4,"price_per_night":432,"stars":2.95},
{"country":"Brazil","city":"Custódia","rental_name":"Lindbergh","date_available":1,"price_per_night":360,"stars":3.78},
{"country":"China","city":"Wuhu","rental_name":"Hansons","date_available":2,"price_per_night":386,"stars":1.15},
{"country":"Poland","city":"Żabia Wola","rental_name":"Jana","date_available":9,"price_per_night":640,"stars":4.35},
{"country":"El Salvador","city":"San Rafael Oriente","rental_name":"Caliangt","date_available":4,"price_per_night":336,"stars":2.92},
{"country":"Rwanda","city":"Musanze","rental_name":"Kings","date_available":4,"price_per_night":795,"stars":3.25},
{"country":"Ecuador","city":"Naranjito","rental_name":"Debs","date_available":10,"price_per_night":475,"stars":2.22},
{"country":"Azerbaijan","city":"Birinci Aşıqlı","rental_name":"Evergreen","date_available":1,"price_per_night":555,"stars":4.35},
{"country":"Russia","city":"Novyy Karachay","rental_name":"4th","date_available":8,"price_per_night":863,"stars":2.07},
{"country":"Georgia","city":"Tsalka","rental_name":"Sullivan","date_available":3,"price_per_night":170,"stars":2.6},
{"country":"France","city":"Marseille","rental_name":"Graceland","date_available":5,"price_per_night":152,"stars":1.53},
{"country":"China","city":"Dongtundu","rental_name":"Banding","date_available":7,"price_per_night":36,"stars":4.85},
{"country":"Croatia","city":"Predavac","rental_name":"Fallview","date_available":9,"price_per_night":444,"stars":3.67},
{"country":"Poland","city":"Czerwieńsk","rental_name":"Morningstar","date_available":1,"price_per_night":704,"stars":1.61},
{"country":"Czech Republic","city":"Rumburk","rental_name":"Ronald Regan","date_available":6,"price_per_night":12,"stars":3.25},
{"country":"Philippines","city":"Mulanay","rental_name":"Florence","date_available":2,"price_per_night":121,"stars":3.62},
{"country":"Thailand","city":"Khuean Ubonrat","rental_name":"Marquette","date_available":10,"price_per_night":545,"stars":3.0},
{"country":"Kazakhstan","city":"Zharkent","rental_name":"Johnson","date_available":8,"price_per_night":825,"stars":2.49},
{"country":"Philippines","city":"Mianay","rental_name":"Eastlawn","date_available":7,"price_per_night":453,"stars":3.11},
{"country":"Afghanistan","city":"Balkh","rental_name":"Cottonwood","date_available":1,"price_per_night":662,"stars":3.96},
{"country":"Thailand","city":"Ban Na Muang","rental_name":"Judy","date_available":7,"price_per_night":970,"stars":1.73},
{"country":"Philippines","city":"Isulan","rental_name":"Summit","date_available":9,"price_per_night":239,"stars":2.91}]
export default data;
